# You can read the Docker Compose documentation at:
#
#   https://docs.docker.com/compose/
#
# Run with file with `docker-compose up -d`.
#
# We use two separate Docker containers: one for the database and one for the
# Misas application.
#

# Uncomment for production
#elasticsearch server
misases_dev:
  image: elasticsearch:2.3.3
  volumes:
    - ./esdata:/usr/share/elasticsearch/data
  ports:
    - 9200
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://212.47.231.164:12201"
#mongo server
misasdb_dev:
  image: mongo:2.6.12
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --replSet test
  ports:
    - 27017
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://212.47.231.164:12201"
#meteor server
misas_dev:
  build: .
  links:
    - misasdb_dev
    - misases_dev
  env_file:
    - ./dev.env
  environment:
    - MONGO_URL=mongodb://misasdb_dev/misas
    - ROOT_URL=http://localhost:3000
    - SEARCH_MONGO_URL=mongodb://misasdb_dev/misas
    - SEARCH_ELASTIC_URL=http://misases_dev:9200
  volumes:
    - ./:/app
  command: meteor
  ports:
    - 3000
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://212.47.231.164:12201"
  labels:
    - "traefik.backend=misasdev"
    - "traefik.port=3000"
    - "traefik.frontend.rule=Host:dev.misas.online"
