misasdb_dev:
  extends:
    file: ../common/docker-compose.yml
    service: misasdb
  volumes:
    - ../../data/runtime/db:/data/db
    - ../../data/dump:/dump

misas_dev:
  build: content
  links:
    - misasdb_dev
  environment:
    - MONGO_URL=mongodb://misasdb_dev/misas
    - ROOT_URL=http://localhost:80
    ports:
      - 3100:80
