FROM ubuntu:xenial 
#mongo needs this locales thing
RUN apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US.UTF-8
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y git-core
RUN curl https://install.meteor.com/ | sh
RUN mkdir -p /etc/misas/ /var/misas/

COPY misas-git.bash misas-meteor-deploy.bash /etc/misas/
WORKDIR /var/misas/
VOLUME /var/misas/
RUN chmod +x /etc/misas/misas-meteor-deploy.bash

EXPOSE 3000
# this script deploys the application on meteor
CMD /etc/misas/misas-meteor-deploy.bash
